'(defvar *b* 7)
(defvar *b* 7)
'(defun    foofun (x) `(list ,x))
(defun    foofun (x) `(list ,x))
'(foofun *b*)
(foofun *b*)
'(defmacro foomac (x) `(list ,x))
(defmacro foomac (x) `(list ,x))
'(foomac *b*)
(foomac *b*)
'(foomac K)
(foomac K)
